inherit_from: "configs/mono/table/base_config.yaml"

Dataset:
  dataset_path: "/media/rpng/RPNG_FLASH_4/datasets/TABLE/table01_all_frames_old/"
  Calibration:
    fx: 416.85
    fy: 414.92
    cx: 421.02
    cy: 237.76
    k1: 0.2624
    k2: -0.9531
    p1: -0.0054
    p2: 0.0026
    k3: 1.1633
    height: 480
    width: 848
    depth_scale: 1000.0
    distorted: False